### ISSUE TITLE
Unused vars, imports not detected

### ISSUE THREAD

**Issue by mosesoak** [Microsoft/vscode-ts-tslint#3]
Possible cause:

Newest version of tslint requires that the --type-check and --project flags are specified in order to show unused imports and variables.

**Comment by egamma** [comment]
Please see the limitations documented in the README

>Due to an issue in the tslint implementation of the no-unused-variable rule (#2649), this rule has to be disabled by the plugin. You can use the typescript compiler options noUnusedLocals and noUnusedParameters instead.
